const js = require('@eslint/js');
const tsParser = require('@typescript-eslint/parser');
const tsPlugin = require('@typescript-eslint/eslint-plugin');
const importX = require('eslint-plugin-import-x');
const jsdoc = require('eslint-plugin-jsdoc');
const prettier = require('eslint-plugin-prettier/recommended');
const globals = require('globals');

// Preserve the active rules from @gravity-ui/eslint-config 3.3 base + prettier.
// React, accessibility and security presets were never enabled in this project.
module.exports = [
    {ignores: ['dist/**', '**/.*']},
    {
        files: ['**/*.{js,cjs,mjs,jsx,ts,tsx,mts}'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            parserOptions: {ecmaFeatures: {jsx: true}},
            globals: {...globals['shared-node-browser'], ...globals.node},
        },
        plugins: {'import-x': importX, jsdoc},
        settings: {
            'import-x/resolver': {node: {extensions: ['.js', '.jsx', '.ts', '.tsx', '.json']}},
            jsdoc: {mode: 'typescript'},
        },
        rules: {
            ...js.configs.recommended.rules,
            'array-callback-return': 2,
            'block-scoped-var': 1,
            complexity: 1,
            'consistent-return': 1,
            eqeqeq: [1, 'always'],
            'guard-for-in': 2,
            'no-caller': 2,
            'no-console': 1,
            'no-div-regex': 1,
            'no-eq-null': 2,
            'no-eval': 1,
            'no-extend-native': 2,
            'no-extra-bind': 1,
            'no-extra-label': 2,
            'no-global-assign': 1,
            'no-implicit-coercion': 1,
            'no-implicit-globals': 1,
            'no-implied-eval': 1,
            'no-iterator': 2,
            'no-labels': 2,
            'no-loop-func': 2,
            'no-new': 2,
            'no-new-func': 1,
            'no-new-wrappers': 2,
            'no-octal-escape': 2,
            'no-param-reassign': [1, {props: true}],
            'no-proto': 2,
            'no-return-assign': [2, 'always'],
            'no-script-url': 2,
            'no-self-compare': 2,
            'no-sequences': 2,
            'no-throw-literal': 1,
            'no-unmodified-loop-condition': 2,
            'no-unused-expressions': 2,
            'no-useless-call': 2,
            'no-useless-concat': 2,
            'no-void': 2,
            'no-with': 2,
            radix: 1,
            'no-label-var': 2,
            'no-shadow': 1,
            'no-shadow-restricted-names': 2,
            'no-undef-init': 2,
            'no-use-before-define': [1, {functions: false}],
            'callback-return': 1,
            'handle-callback-err': 1,
            'no-new-require': 2,
            'no-path-concat': 1,
            camelcase: [2, {properties: 'never'}],
            'max-depth': [1, {maximum: 5}],
            'no-array-constructor': 1,
            'no-bitwise': 2,
            'no-lonely-if': 1,
            'no-negated-condition': 1,
            'no-nested-ternary': 1,
            'no-restricted-syntax': [2, 'WithStatement'],
            'no-unneeded-ternary': 2,
            'sort-imports': [2, {ignoreDeclarationSort: true}],
            'no-useless-constructor': 2,
            'no-var': 2,
            'prefer-const': 2,
            'prefer-rest-params': 2,
            'prefer-spread': 2,
            'require-yield': 1,
            'import-x/no-duplicates': [2, {considerQueryString: true}],
            'import-x/no-extraneous-dependencies': [2, {includeTypes: true}],
            'no-object-constructor': 1,
            'new-cap': 'off',
            'no-empty': 'off',
            'require-atomic-updates': 'off',
            'no-inner-declarations': ['error', 'functions', {blockScopedFunctions: 'disallow'}],
            'no-constant-condition': ['error', {checkLoops: 'all'}],
            // ESLint 9 removed valid-jsdoc; preserve its syntax, parameter and return checks.
            'jsdoc/check-param-names': ['warn', {checkDestructured: false}],
            'jsdoc/require-param': [
                'warn',
                {checkDestructured: false, checkDestructuredRoots: false},
            ],
            'jsdoc/require-returns': ['warn', {forceRequireReturn: true}],
            'jsdoc/require-param-type': 'warn',
            'jsdoc/require-returns-type': 'warn',
            'jsdoc/valid-types': 'warn',
        },
    },
    {
        files: ['**/*.{ts,tsx,mts}'],
        languageOptions: {parser: tsParser},
        plugins: {'@typescript-eslint': tsPlugin},
        rules: {
            strict: 0,
            'no-undef': 0,
            'no-dupe-class-members': 0,
            'no-array-constructor': 0,
            'no-loop-func': 0,
            'no-redeclare': 0,
            'no-shadow': 0,
            'no-unused-expressions': 0,
            'no-unused-vars': 0,
            'no-use-before-define': 0,
            'no-useless-constructor': 0,
            '@typescript-eslint/no-array-constructor': 1,
            '@typescript-eslint/no-loop-func': 2,
            '@typescript-eslint/no-redeclare': 2,
            '@typescript-eslint/no-shadow': 1,
            '@typescript-eslint/no-unused-expressions': 2,
            '@typescript-eslint/no-unused-vars': [
                2,
                {argsIgnorePattern: '^_', varsIgnorePattern: '^_'},
            ],
            '@typescript-eslint/no-use-before-define': [1, {functions: false}],
            '@typescript-eslint/no-useless-constructor': 2,
            '@typescript-eslint/naming-convention': [
                2,
                {selector: 'typeLike', format: ['PascalCase'], leadingUnderscore: 'forbid'},
            ],
            '@typescript-eslint/member-ordering': [
                2,
                {
                    default: [
                        'public-static-field',
                        'protected-static-field',
                        'private-static-field',
                        'public-static-method',
                        'protected-static-method',
                        'private-static-method',
                        'public-instance-field',
                        'protected-instance-field',
                        'private-instance-field',
                        'constructor',
                        'public-instance-method',
                        'protected-instance-method',
                        'private-instance-method',
                    ],
                },
            ],
            '@typescript-eslint/explicit-member-accessibility': [2, {accessibility: 'no-public'}],
            '@typescript-eslint/consistent-type-assertions': 2,
            '@typescript-eslint/no-inferrable-types': 2,
            '@typescript-eslint/no-namespace': 2,
            '@typescript-eslint/no-non-null-assertion': 1,
            '@typescript-eslint/parameter-properties': 2,
            '@typescript-eslint/triple-slash-reference': 2,
            '@typescript-eslint/prefer-namespace-keyword': 2,
            '@typescript-eslint/no-explicit-any': 'off',
            'jsdoc/require-param-type': 'off',
            'jsdoc/require-returns-type': 'off',
        },
    },
    {
        files: ['src/**/*.test.{ts,tsx}', 'src/**/tests/**/*.{ts,tsx}'],
        languageOptions: {globals: globals.vitest},
    },
    {
        files: ['**/*.{js,cjs}'],
        languageOptions: {sourceType: 'commonjs'},
    },
    prettier,
];
